### ISSUE TITLE
Is this project stopped?

### ISSUE THREAD

**Issue by xiasummer** [escheffel/pymaclab#34]
I found this project not updating for 5 years from now. Has it been stopped totally?

**Comment by apsql** [comment]
[Bump]
I'm interested in this project, too. Is there a particular reason for which development stopped?

**Comment by escheffel** [comment]
Hi there,

The project was paused for a while, but I am planning to seriously update
the code in the summer of 2018. At a minimum I want to make sure that the
code is updated so as to work with the latest versions of Python and all of
the dependent libraries.

Eric - PyMacLab owner and developer

On Mon, Apr 23, 2018 at 7:49 PM, Andrea Pasqualini <notifications@github.com

**Comment by escheffel** [comment]
Hi there,

I have just now prepared, committed and pushed a relatively superficial revision of the setup.py file in order to update the installation routine to take into account the latest package dependency versions. I have also updated the INSTALL.txt file. Following this, I was able to successfully import the library into an IPython session and also to load and solve DSGE models. I still need to update the documentation. You can for example import a model and solve it using:

rbc1 = pm.newMOD(models.stable.rbc2)
rbc1.modsolvers.forkleind.solve()

More work to be done... Eric
